name: E2E Test Matrix Runner

on:
  # Schedule nightly runs
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC every day

jobs:
  matrix-runner:
    strategy:
      fail-fast: false
      matrix:
        arkd-version: [
          'v0.5.9',
          'master'
          # Add more versions as needed
        ]

    uses: ./.github/workflows/e2e-core.yml
    with:
      arkd-version: ${{ matrix.arkd-version }}
