name: E2E Test Matrix Runner

on:
  # Schedule nightly runs
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC every day

jobs:
  matrix-runner:
    strategy:
      fail-fast: false
      matrix:
        arkd-version: [
          'master',
          'v0.8.0-rc.1'
          # Add more versions as needed
        ]

    uses: ./.github/workflows/e2e-core.yml
    with:
      arkd-version: ${{ matrix.arkd-version }}
